name: unit-test
run-name: ${{ github.actor }} is running unit testing
on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.20" # The Go version to download (if necessary) and use.
      - run: mkdir build
      - run: go test ./...
